name: node-gha

on:
  push:
    paths:
      - node-gha/Dockerfile
      - .github/workflows/node-gha.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          path: node-gha
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: madscience/ci-images/node-gha
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]

    runs-on: ubuntu-latest
    steps:
      - name: Publish release tags to GitHub Package Registry
        uses: flownative/action-docker-publish-semver@v1.2.0
        with:
          tag_ref: ${{ github.ref }}
          tag_latest: yes
          #tag_custom: 'some-custom-tag'

          source_image_name: docker.pkg.github.com/madscience/ci-images/node-gha
          source_registry_username: ${{ github.actor }}
          source_registry_password: ${{ secrets.GITHUB_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: docker.pkg.github.com/madscience/ci-images/node-gha
          target_registry_username: ${{ github.actor }}
          target_registry_password: ${{ secrets.GITHUB_TOKEN }}
          target_registry_endpoint: https://docker.pkg.github.com/v2/
