name: node-gha

on:
  push:
    paths:
      - node-gha/Dockerfile
      - .github/workflows/node-gha.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: node-gha/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: madscience/ci-images/node-gha
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
